export const AllServices = [
	{ value: 'RENOVACIÓN DE LICENCIA', label: 'RENOVACIÓN DE LICENCIA' },
	{
		value: 'LICENCIA (EXAMEN PRACTICO)',
		label: 'LICENCIA (EXAMEN PRÁCTICO)',
	},
	{ value: 'DUPLICADOS', label: 'DUPLICADOS' },
	{ value: 'CARNET DE APRENDIZAJE', label: 'CARNET DE APRENDIZAJE' },
	{
		value: 'CAMBIO DE CATEGORIA 02 A 03',
		label: 'CAMBIO DE CATEGORÍA 02 A 03',
	},
	{
		value: 'CAMBIO DE CATEGORIA 03 A 04',
		label: 'CAMBIO DE CATEGORÍA 03 A 04',
	},
	{
		value: 'CAMBIO LICENCIA MILITAR A CIVIL',
		label: 'CAMBIO LICENCIA MILITAR A CIVIL',
	},
	{
		value: 'CAMBIO LICENCIA EXTRANJERA A DOMINICANA',
		label: 'CAMBIO LICENCIA EXTRANJERA A DOMINICANA',
	},
	{
		value: 'LICENCIA CONDUCIR DIPLOMATICA',
		label: 'LICENCIA CONDUCIR DIPLOMATICA',
	},
	{ value: 'NUEVO MOTORISTA', label: 'NUEVO MOTORISTA' },
	{
		value: 'LICENCIA POLICIAS Y MILITARES',
		label: 'LICENCIA POLICIAS Y MILITARES',
	},
];