export const objServiceByOffice = {
	RenovacionDeLicencia: [
		{ value: 'azua', label: 'Azua' },
		{ value: 'barahona', label: 'Barahona' },
		{ value: 'blue mall', label: 'Blue Mall' },
		{ value: 'españa-madrid', label: 'España-Madrid' },
		{ value: 'higüey', label: 'Higüey' },
		{ value: 'la romana', label: 'La Romana' },
		{ value: 'la vega', label: 'La Vega' },
		{ value: 'mao', label: 'Mao' },
		{ value: 'megacentro', label: 'Megacentro' },
		{ value: 'multicentro churchill', label: 'Multicentro Churchill' },
		{ value: 'nagua', label: 'Nagua' },
		{ value: 'new york', label: 'New York' },
		{ value: 'oficina central', label: 'Oficina Central' },
		{ value: 'puerto plata', label: 'Puerto Plata' },
		{ value: 'sambil', label: 'Sambil' },
		{ value: 'san francisco', label: 'San Francisco' },
		{ value: 'san juan de la maguana', label: 'San Juan de la Maguana' },
		{ value: 'santiago', label: 'Santiago' },
	],
	ExamePractico: [
		{ value: 'azua', label: 'Azua' },
		{ value: 'barahona', label: 'Barahona' },
		{ value: 'blue mall', label: 'Blue Mall' },
		{ value: 'higüey', label: 'Higüey' },
		{ value: 'la romana', label: 'La Romana' },
		{ value: 'la vega', label: 'La Vega' },
		{ value: 'mao', label: 'Mao' },
		{ value: 'nagua', label: 'Nagua' },
		{ value: 'oficina central', label: 'Oficina Central' },
		{ value: 'puerto plata', label: 'Puerto Plata' },
		{ value: 'san francisco', label: 'San Francisco' },
		{ value: 'san juan de la maguana', label: 'San Juan de la Maguana' },
		{ value: 'santiago', label: 'Santiago' },
	],
	Duplicados: [
		{ value: 'azua', label: 'Azua' },
		{ value: 'barahona', label: 'Barahona' },
		{ value: 'blue mall', label: 'Blue Mall' },
		{ value: 'españa-madrid', label: 'España-Madrid' },
		{ value: 'higüey', label: 'Higüey' },
		{ value: 'la romana', label: 'La Romana' },
		{ value: 'la vega', label: 'La Vega' },
		{ value: 'mao', label: 'Mao' },
		{ value: 'megacentro', label: 'Megacentro' },
		{ value: 'multicentro churchill', label: 'Multicentro Churchill' },
		{ value: 'nagua', label: 'Nagua' },
		{ value: 'new york', label: 'New York' },
		{ value: 'oficina central', label: 'Oficina Central' },
		{ value: 'puerto plata', label: 'Puerto Plata' },
		{ value: 'sambil', label: 'Sambil' },
		{ value: 'san francisco', label: 'San Francisco' },
		{ value: 'san juan de la maguana', label: 'San Juan de la Maguana' },
		{ value: 'santiago', label: 'Santiago' },
	],
	CarnetDeApredizaje: [
		{ value: 'azua', label: 'Azua' },
		{ value: 'barahona', label: 'Barahona' },
		{ value: 'blue mall', label: 'Blue Mall' },
		{ value: 'higüey', label: 'Higüey' },
		{ value: 'la romana', label: 'La Romana' },
		{ value: 'la vega', label: 'La Vega' },
		{ value: 'mao', label: 'Mao' },
		{ value: 'nagua', label: 'Nagua' },
		{ value: 'oficina central', label: 'Oficina Central' },
		{ value: 'puerto plata', label: 'Puerto Plata' },
		{ value: 'san francisco', label: 'San Francisco' },
		{ value: 'san juan de la maguana', label: 'San Juan de la Maguana' },
		{ value: 'santiago', label: 'Santiago' },
	],
	CambioDeCategoria02A03: [
		{ value: 'azua', label: 'Azua' },
		{ value: 'la romana', label: 'La Romana' },
		{ value: 'oficina central', label: 'Oficina Central' },
		{ value: 'puerto plata', label: 'Puerto Plata' },
		{ value: 'san francisco', label: 'San Francisco' },
		{ value: 'santiago', label: 'Santiago' },
	],
	CambioDeCategoria03A04: [
		{ value: 'azua', label: 'Azua' },
		{ value: 'oficina central', label: 'Oficina Central' },
		{ value: 'puerto plata', label: 'Puerto Plata' },
		{ value: 'santiago', label: 'Santiago' },
	],
	CambioLicenciaMilitarACivil: [
		{ value: 'azua', label: 'Azua' },
		{ value: 'oficina central', label: 'Oficina Central' },
	],
	CambioLicenciaExtranjeraADominicana: [
		{ value: 'azua', label: 'Azua' },
		{ value: 'oficina central', label: 'Oficina Central' },
		{ value: 'santiago', label: 'Santiago' },
	],
	LicenciaConducirDiplomatica: [
		{ value: 'azua', label: 'Azua' },
		{ value: 'oficina central', label: 'Oficina Central' },
		{ value: 'san francisco', label: 'San Francisco' },
		{ value: 'santiago', label: 'Santiago' },
	],
	NuevoMotorista: [
		{ value: 'azua', label: 'Azua' },
		{ value: 'barahona', label: 'Barahona' },
		{ value: 'mao', label: 'Mao' },
		{ value: 'nagua', label: 'Nagua' },
		{ value: 'oficina central', label: 'Oficina Central' },
		{ value: 'puerto plata', label: 'Puerto Plata' },
		{ value: 'san francisco', label: 'San Francisco' },
		{ value: 'san juan de la maguana', label: 'San Juan de la Maguana' },
		{ value: 'santiago', label: 'Santiago' },
	],
	LicenciaPoliciaYMilitares: [
		{ value: 'azua', label: 'Azua' },
		{ value: 'barahona', label: 'Barahona' },
		{ value: 'mao', label: 'Mao' },
		{ value: 'nagua', label: 'Nagua' },
		{ value: 'oficina central', label: 'Oficina Central' },
		{ value: 'puerto plata', label: 'Puerto Plata' },
		{ value: 'san juan de la maguana', label: 'San Juan de la Maguana' },
		{ value: 'santiago', label: 'Santiago' },
	],
};

export const optionServiceByOffice = {
	'RENOVACIÓN DE LICENCIA': objServiceByOffice.RenovacionDeLicencia,
	'LICENCIA (EXAMEN PRACTICO)': objServiceByOffice.ExamePractico,
	DUPLICADOS: objServiceByOffice.Duplicados,
    'CARNET DE APRENDIZAJE': objServiceByOffice.CarnetDeApredizaje,

	'CAMBIO DE CATEGORIA 02 A 03': objServiceByOffice.CambioDeCategoria02A03,
	'CAMBIO DE CATEGORIA 03 A 04': objServiceByOffice.CambioDeCategoria03A04,
	'CAMBIO LICENCIA MILITAR A CIVIL': objServiceByOffice.CambioLicenciaMilitarACivil,
	'CAMBIO LICENCIA EXTRANJERA A DOMINICANA': objServiceByOffice.CambioLicenciaExtranjeraADominicana,

	'LICENCIA CONDUCIR DIPLOMATICA': objServiceByOffice.LicenciaConducirDiplomatica,
	'NUEVO MOTORISTA': objServiceByOffice.NuevoMotorista,
	'LICENCIA POLICIAS Y MILITARES': objServiceByOffice.LicenciaPoliciaYMilitares,
};
