export const optionsOffices = [
	{ value: 'azua', label: 'Azua' },
	{ value: 'barahona', label: 'Barahona' },
	{ value: 'blue mall', label: 'Blue Mall' },
	{ value: 'españa-madrid', label: 'España-Madrid' },
	{ value: 'higüey', label: 'Higüey' },
	{ value: 'la romana', label: 'La Romana' },
	{ value: 'la vega', label: 'La Vega' },
	{ value: 'mao', label: 'Mao' },
	{ value: 'megacentro', label: 'Megacentro' },
	{ value: 'multicentro churchill', label: 'Multicentro Churchill' },
	{ value: 'nagua', label: 'Nagua' },
	{ value: 'new york', label: 'New York' },
	{ value: 'oficina central', label: 'Oficina Central' },
	{ value: 'puerto plata', label: 'Puerto Plata' },
	{ value: 'sambil', label: 'Sambil' },
	{ value: 'san francisco', label: 'San Francisco' },
	{ value: 'san juan de la maguana', label: 'San Juan de la Maguana' },
	{ value: 'santiago', label: 'Santiago' },
];